# Generated by Django 4.2.7 on 2025-12-18 22:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('item_type', models.CharField(choices=[('MINER', 'ماینر'), ('GENERATOR', 'ژنراتور/باتری'), ('SKIN', 'اسکین'), ('AVATAR', 'آواتار'), ('LOOT', 'لوت باکس'), ('MATERIAL', 'متریال'), ('ENERGY', 'پک انرژی'), ('BUFF', 'باف/Artifact')], max_length=20)),
                ('item_code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='items/')),
                ('price_diamonds', models.IntegerField(default=0)),
                ('sell_price', models.IntegerField(default=0)),
                ('stock', models.IntegerField(default=-1)),
                ('is_hidden_in_shop', models.BooleanField(default=False)),
                ('mining_rate', models.IntegerField(default=0, help_text='تولید سکه در ساعت')),
                ('electricity_consumption', models.IntegerField(default=0, help_text='مصرف برق وات')),
                ('miner_diamond_chance', models.FloatField(default=0, help_text='شانس پیدا کردن الماس (درصد در ساعت)')),
                ('buff_mining_speed', models.FloatField(default=0, help_text='درصد افزایش سرعت ماین')),
                ('buff_click_coins', models.IntegerField(default=0, help_text='سکه اضافه در هر کلیک')),
                ('buff_luck', models.FloatField(default=0, help_text='درصد افزایش شانس (الماس و دراپ)')),
                ('can_drop', models.BooleanField(default=False)),
                ('drop_chance', models.FloatField(default=0, help_text='شانس دراپ شدن در هر کلیک (درصد)')),
            ],
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('reward_coins', models.IntegerField(default=0)),
                ('reward_diamonds', models.IntegerField(default=0)),
                ('max_uses', models.IntegerField(default=100)),
                ('current_uses', models.IntegerField(default=0)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsedPromo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.promocode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coins', models.BigIntegerField(default=0)),
                ('diamonds', models.IntegerField(default=0)),
                ('energy', models.IntegerField(default=1000)),
                ('max_energy', models.IntegerField(default=1000)),
                ('electricity', models.IntegerField(default=5000)),
                ('max_electricity', models.IntegerField(default=5000)),
                ('last_mined_at', models.DateTimeField(blank=True, null=True)),
                ('last_daily_claim', models.DateTimeField(blank=True, null=True)),
                ('daily_streak', models.IntegerField(default=0)),
                ('avatar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avatar_users', to='game.gameitem')),
                ('equipped_skin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_by_users', to='game.gameitem')),
                ('slot_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slot1_users', to='game.gameitem')),
                ('slot_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slot2_users', to='game.gameitem')),
                ('slot_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slot3_users', to='game.gameitem')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='playerprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MarketListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.gameitem')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.playerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.gameitem')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.playerprofile')),
            ],
            options={
                'unique_together': {('player', 'item')},
            },
        ),
    ]
