# Generated by Django 4.2.7 on 2025-12-20 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_achievement_auctionlisting_userachievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
