# Generated by Django 4.2.7 on 2025-12-20 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_inventory_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='click_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='click_xp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='click_xp_to_next',
            field=models.IntegerField(default=100),
        ),
    ]
