# Generated by Django 4.2.7 on 2025-12-20 21:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0004_playerprofile_click_level_playerprofile_click_xp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='active_boost_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='boost_multiplier',
            field=models.FloatField(default=1.0),
        ),
        migrations.CreateModel(
            name='UserQuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('quest_type', models.CharField(choices=[('CLICK', 'Click'), ('MINE', 'Mine')], max_length=10)),
                ('goal', models.IntegerField(default=0)),
                ('progress', models.IntegerField(default=0)),
                ('reward_coins', models.IntegerField(default=0)),
                ('reward_diamonds', models.IntegerField(default=0)),
                ('reward_xp', models.IntegerField(default=0)),
                ('reset_at', models.DateField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'code')},
            },
        ),
    ]
