# Generated by Django 5.2.9 on 2025-12-28 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_playerprofile_active_boost_until_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrestigeMultiplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prestige_count', models.IntegerField(default=0)),
                ('prestige_multiplier', models.FloatField(default=1.0)),
                ('last_prestige_date', models.DateTimeField(blank=True, null=True)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prestige', to='game.playerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PrestigeReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prestige_level', models.IntegerField()),
                ('reward_type', models.CharField(choices=[('DIAMONDS', 'Diamonds'), ('BONUS_MULTIPLIER', 'Bonus Multiplier'), ('SPECIAL_ITEM', 'Special Item')], max_length=20)),
                ('reward_amount', models.IntegerField()),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'unique_together': {('prestige_level', 'reward_type')},
            },
        ),
    ]
